{{- if .Values.restdefinitions.identity_provider.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-identity-provider
  labels:
    {{- include "openstack-keystone-operator-kog.labels" . | nindent 4 }}
data:
  identityprovider.yaml: |
{{ tpl (.Files.Get "assets/identity-provider.yaml") . | indent 4 }}
{{- end }}
