{{- if .Values.restdefinitions.role_assignment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-role-assignment
  labels:
    {{- include "openstack-keystone-operator-kog.labels" . | nindent 4 }}
data:
  roleassignment.yaml: |
{{ tpl (.Files.Get "assets/role-assignment.yaml") . | indent 4 }}
{{- end }}
