{{- if .Values.restdefinitions.domain.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-domain
  labels:
    {{- include "openstack-keystone-operator-kog.labels" . | nindent 4 }}
data:
  domain.yaml: |
{{ tpl (.Files.Get "assets/domain.yaml") . | indent 4 }}
{{- end }}
