{{- if .Values.restdefinitions.application_credential.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-application-credential
  labels:
    {{- include "openstack-keystone-operator-kog.labels" . | nindent 4 }}
data:
  appcredential.yaml: |
{{ tpl (.Files.Get "assets/application-credential.yaml") . | indent 4 }}
{{- end }}
